"""
Generate src/lib/refDirectory.ts from wbb_outreach_final.csv so a visit ping can
say "Carter Caplan · SMU · DOBO" instead of a cryptic ref.

PUBLIC FIELDS ONLY — name, school, role. Emails are deliberately excluded: this
map ships in the client bundle, and the CSV (with emails) stays gitignored.
Re-run after editing the CSV:  python3 scripts/og/build_ref_directory.py
"""
from pathlib import Path
import csv
import json

ROOT = Path(__file__).resolve().parents[2]
CSV = ROOT / 'wbb_outreach_final.csv'
OUT = ROOT / 'src' / 'lib' / 'refDirectory.ts'


def main() -> int:
    rows = list(csv.DictReader(CSV.open(newline='')))
    directory = {
        r['ref']: {'name': r['name'], 'school': r['school'], 'role': r['role']}
        for r in rows
        if r.get('ref')
    }
    # Stable ordering keeps the generated file diff-friendly.
    body = ',\n'.join(
        f'  {json.dumps(ref)}: {json.dumps(info, ensure_ascii=False)}'
        for ref, info in sorted(directory.items())
    )
    OUT.write_text(
        '// AUTO-GENERATED by scripts/og/build_ref_directory.py — do not edit by hand.\n'
        '// Public outreach info only (name, school, role). NO emails: this ships in\n'
        '// the client bundle, while wbb_outreach_final.csv (with emails) is gitignored.\n'
        '// Used by trackVisit() to label per-recipient visit pings.\n\n'
        'export interface RefInfo {\n'
        '  name: string\n'
        '  school: string\n'
        '  role: string\n'
        '}\n\n'
        'export const REF_DIRECTORY: Record<string, RefInfo> = {\n'
        f'{body},\n'
        '}\n'
    )
    print(f'Wrote {len(directory)} refs to {OUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
